# Generated by Django 5.2.7 on 2025-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('slide_type', models.CharField(choices=[('main', 'Main Slideshow'), ('banner', 'Static Banner')], default='main', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('link', models.CharField(blank=True, help_text='Optional link URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slideshow Image',
                'verbose_name_plural': 'Slideshow Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
