# Generated by Django 5.2.7 on 2025-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_picture_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
