# Generated by Django 5.2.7 on 2025-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_product', 'New Product'), ('order_update', 'Order Update'), ('new_deal', 'New Deal'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('new_user', 'New User'), ('system', 'System Notification')], max_length=20),
        ),
    ]
