# Generated by Django 5.2.7 on 2025-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_screenshot_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_free_delivery', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount for free delivery', max_digits=10)),
                ('estimated_days', models.CharField(help_text="Estimated delivery time (e.g., '3-5 days')", max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Fee',
                'verbose_name_plural': 'Delivery Fees',
                'ordering': ['state', 'city'],
                'unique_together': {('city', 'state')},
            },
        ),
    ]
