# Generated by Django 5.2.7 on 2025-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliveryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deal_usage_counted',
            field=models.BooleanField(default=False, help_text='Track if deal usage has been counted for this order'),
        ),
    ]
