# Generated by Django 5.2.7 on 2025-10-27 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deal_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Deal')], default='percentage', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount discount', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured deals section')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this deal can be used', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('badge_text', models.CharField(blank=True, help_text="Custom badge text (e.g., 'HOT DEAL')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='deals', to='products.product')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
